// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that resolves a company name to an email address.
 *
 * - resolveCompanyEmail - A function that handles the company email resolution process.
 * - ResolveCompanyEmailInput - The input type for the resolveCompanyEmail function.
 * - ResolveCompanyEmailOutput - The return type for the resolveCompanyEmail function.
 */

import { z } from 'zod';
import { model } from '@/lib/genai';

const ResolveCompanyEmailInputSchema = z.object({
  companyName: z.string().min(1, 'Company name is required'),
});
export type ResolveCompanyEmailInput = z.infer<typeof ResolveCompanyEmailInputSchema>;

const ResolveCompanyEmailOutputSchema = z.object({
  emailAddress: z.string().email('Must be a valid email address'),
});
export type ResolveCompanyEmailOutput = z.infer<typeof ResolveCompanyEmailOutputSchema>;

export async function resolveCompanyEmail(input: ResolveCompanyEmailInput): Promise<ResolveCompanyEmailOutput> {
  try {
    // Input validation
    const validatedInput = ResolveCompanyEmailInputSchema.parse(input);

    // Using the pre-configured model from lib/genai

    const prompt = `You are an expert at finding company email addresses.
    For the company "${validatedInput.companyName}", provide their most likely general contact email address.
    Only return the email address, nothing else. If you can't determine it with high confidence, return support@${validatedInput.companyName.toLowerCase().replace(/\s+/g, '')}.com
    `;

    // Generate content
    const result = await model.generateContent(prompt);
    const response = result.response;
    const email = response.text().trim();

    // Validate output
    const output = ResolveCompanyEmailOutputSchema.parse({ emailAddress: email });
    return output;

  } catch (error) {
    console.error('Company email resolution error:', error);
    // Fallback to a default format if AI generation fails
    const sanitizedCompanyName = input.companyName.toLowerCase().replace(/[^a-z0-9]/g, '');
    return {
      emailAddress: `contact@${sanitizedCompanyName}.com`
    };
  }
}
